package com.ccbs.am.domain;

public class AmMenuInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_menu.num_menuid
     *
     * @mbggenerated
     */
    private String numMenuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_menu.txt_menuname
     *
     * @mbggenerated
     */
    private String txtMenuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_menu.vlu_url
     *
     * @mbggenerated
     */
    private String vluUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_menu.cod_seq
     *
     * @mbggenerated
     */
    private Short codSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_menu.ind_msk_sts
     *
     * @mbggenerated
     */
    private String indMskSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_menu.ind_isleaf
     *
     * @mbggenerated
     */
    private String indIsleaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_menu.cod_categroy
     *
     * @mbggenerated
     */
    private String codCategroy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_menu.date_upd_last
     *
     * @mbggenerated
     */
    private String dateUpdLast;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_menu.num_menuid
     *
     * @return the value of t_am_menu.num_menuid
     *
     * @mbggenerated
     */
    public String getNumMenuid() {
        return numMenuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_menu.num_menuid
     *
     * @param numMenuid the value for t_am_menu.num_menuid
     *
     * @mbggenerated
     */
    public void setNumMenuid(String numMenuid) {
        this.numMenuid = numMenuid == null ? null : numMenuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_menu.txt_menuname
     *
     * @return the value of t_am_menu.txt_menuname
     *
     * @mbggenerated
     */
    public String getTxtMenuname() {
        return txtMenuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_menu.txt_menuname
     *
     * @param txtMenuname the value for t_am_menu.txt_menuname
     *
     * @mbggenerated
     */
    public void setTxtMenuname(String txtMenuname) {
        this.txtMenuname = txtMenuname == null ? null : txtMenuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_menu.vlu_url
     *
     * @return the value of t_am_menu.vlu_url
     *
     * @mbggenerated
     */
    public String getVluUrl() {
        return vluUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_menu.vlu_url
     *
     * @param vluUrl the value for t_am_menu.vlu_url
     *
     * @mbggenerated
     */
    public void setVluUrl(String vluUrl) {
        this.vluUrl = vluUrl == null ? null : vluUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_menu.cod_seq
     *
     * @return the value of t_am_menu.cod_seq
     *
     * @mbggenerated
     */
    public Short getCodSeq() {
        return codSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_menu.cod_seq
     *
     * @param codSeq the value for t_am_menu.cod_seq
     *
     * @mbggenerated
     */
    public void setCodSeq(Short codSeq) {
        this.codSeq = codSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_menu.ind_msk_sts
     *
     * @return the value of t_am_menu.ind_msk_sts
     *
     * @mbggenerated
     */
    public String getIndMskSts() {
        return indMskSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_menu.ind_msk_sts
     *
     * @param indMskSts the value for t_am_menu.ind_msk_sts
     *
     * @mbggenerated
     */
    public void setIndMskSts(String indMskSts) {
        this.indMskSts = indMskSts == null ? null : indMskSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_menu.ind_isleaf
     *
     * @return the value of t_am_menu.ind_isleaf
     *
     * @mbggenerated
     */
    public String getIndIsleaf() {
        return indIsleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_menu.ind_isleaf
     *
     * @param indIsleaf the value for t_am_menu.ind_isleaf
     *
     * @mbggenerated
     */
    public void setIndIsleaf(String indIsleaf) {
        this.indIsleaf = indIsleaf == null ? null : indIsleaf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_menu.cod_categroy
     *
     * @return the value of t_am_menu.cod_categroy
     *
     * @mbggenerated
     */
    public String getCodCategroy() {
        return codCategroy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_menu.cod_categroy
     *
     * @param codCategroy the value for t_am_menu.cod_categroy
     *
     * @mbggenerated
     */
    public void setCodCategroy(String codCategroy) {
        this.codCategroy = codCategroy == null ? null : codCategroy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_menu.date_upd_last
     *
     * @return the value of t_am_menu.date_upd_last
     *
     * @mbggenerated
     */
    public String getDateUpdLast() {
        return dateUpdLast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_menu.date_upd_last
     *
     * @param dateUpdLast the value for t_am_menu.date_upd_last
     *
     * @mbggenerated
     */
    public void setDateUpdLast(String dateUpdLast) {
        this.dateUpdLast = dateUpdLast == null ? null : dateUpdLast.trim();
    }
}