package com.ccbs.am.domain;

public class AmPremRoleInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_prem_role.num_roleid
     *
     * @mbggenerated
     */
    private String numRoleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_prem_role.num_premid
     *
     * @mbggenerated
     */
    private String numPremid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_prem_role.num_roleid
     *
     * @return the value of t_am_prem_role.num_roleid
     *
     * @mbggenerated
     */
    public String getNumRoleid() {
        return numRoleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_prem_role.num_roleid
     *
     * @param numRoleid the value for t_am_prem_role.num_roleid
     *
     * @mbggenerated
     */
    public void setNumRoleid(String numRoleid) {
        this.numRoleid = numRoleid == null ? null : numRoleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_prem_role.num_premid
     *
     * @return the value of t_am_prem_role.num_premid
     *
     * @mbggenerated
     */
    public String getNumPremid() {
        return numPremid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_prem_role.num_premid
     *
     * @param numPremid the value for t_am_prem_role.num_premid
     *
     * @mbggenerated
     */
    public void setNumPremid(String numPremid) {
        this.numPremid = numPremid == null ? null : numPremid.trim();
    }
}