package com.ccbs.am.domain;

public class AmPremInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_premision.num_premid
     *
     * @mbggenerated
     */
    private String numPremid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_premision.txt_prename
     *
     * @mbggenerated
     */
    private String txtPrename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_premision.cod_categroy
     *
     * @mbggenerated
     */
    private String codCategroy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_premision.ind_msk_sts
     *
     * @mbggenerated
     */
    private String indMskSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_premision.date_upd_last
     *
     * @mbggenerated
     */
    private String dateUpdLast;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_premision.num_premid
     *
     * @return the value of t_am_premision.num_premid
     *
     * @mbggenerated
     */
    public String getNumPremid() {
        return numPremid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_premision.num_premid
     *
     * @param numPremid the value for t_am_premision.num_premid
     *
     * @mbggenerated
     */
    public void setNumPremid(String numPremid) {
        this.numPremid = numPremid == null ? null : numPremid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_premision.txt_prename
     *
     * @return the value of t_am_premision.txt_prename
     *
     * @mbggenerated
     */
    public String getTxtPrename() {
        return txtPrename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_premision.txt_prename
     *
     * @param txtPrename the value for t_am_premision.txt_prename
     *
     * @mbggenerated
     */
    public void setTxtPrename(String txtPrename) {
        this.txtPrename = txtPrename == null ? null : txtPrename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_premision.cod_categroy
     *
     * @return the value of t_am_premision.cod_categroy
     *
     * @mbggenerated
     */
    public String getCodCategroy() {
        return codCategroy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_premision.cod_categroy
     *
     * @param codCategroy the value for t_am_premision.cod_categroy
     *
     * @mbggenerated
     */
    public void setCodCategroy(String codCategroy) {
        this.codCategroy = codCategroy == null ? null : codCategroy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_premision.ind_msk_sts
     *
     * @return the value of t_am_premision.ind_msk_sts
     *
     * @mbggenerated
     */
    public String getIndMskSts() {
        return indMskSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_premision.ind_msk_sts
     *
     * @param indMskSts the value for t_am_premision.ind_msk_sts
     *
     * @mbggenerated
     */
    public void setIndMskSts(String indMskSts) {
        this.indMskSts = indMskSts == null ? null : indMskSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_premision.date_upd_last
     *
     * @return the value of t_am_premision.date_upd_last
     *
     * @mbggenerated
     */
    public String getDateUpdLast() {
        return dateUpdLast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_premision.date_upd_last
     *
     * @param dateUpdLast the value for t_am_premision.date_upd_last
     *
     * @mbggenerated
     */
    public void setDateUpdLast(String dateUpdLast) {
        this.dateUpdLast = dateUpdLast == null ? null : dateUpdLast.trim();
    }
}