package com.ccbs.am.domain;

public class AmPremRoleInfo extends AmPremRoleInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_prem_role.ind_msk_proc
     *
     * @mbggenerated
     */
    private String indMskProc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_prem_role.date_upd_last
     *
     * @mbggenerated
     */
    private String dateUpdLast;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_prem_role.ind_msk_proc
     *
     * @return the value of t_am_prem_role.ind_msk_proc
     *
     * @mbggenerated
     */
    public String getIndMskProc() {
        return indMskProc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_prem_role.ind_msk_proc
     *
     * @param indMskProc the value for t_am_prem_role.ind_msk_proc
     *
     * @mbggenerated
     */
    public void setIndMskProc(String indMskProc) {
        this.indMskProc = indMskProc == null ? null : indMskProc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_prem_role.date_upd_last
     *
     * @return the value of t_am_prem_role.date_upd_last
     *
     * @mbggenerated
     */
    public String getDateUpdLast() {
        return dateUpdLast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_prem_role.date_upd_last
     *
     * @param dateUpdLast the value for t_am_prem_role.date_upd_last
     *
     * @mbggenerated
     */
    public void setDateUpdLast(String dateUpdLast) {
        this.dateUpdLast = dateUpdLast == null ? null : dateUpdLast.trim();
    }
}