package com.ccbs.am.domain;

public class AmRoleInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_role.num_roleid
     *
     * @mbggenerated
     */
    private String numRoleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_role.txt_rolename
     *
     * @mbggenerated
     */
    private String txtRolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_role.vlu_roletype
     *
     * @mbggenerated
     */
    private String vluRoletype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_role.ind_msk_sts
     *
     * @mbggenerated
     */
    private String indMskSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_role.date_upd_last
     *
     * @mbggenerated
     */
    private String dateUpdLast;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_role.num_roleid
     *
     * @return the value of t_am_role.num_roleid
     *
     * @mbggenerated
     */
    public String getNumRoleid() {
        return numRoleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_role.num_roleid
     *
     * @param numRoleid the value for t_am_role.num_roleid
     *
     * @mbggenerated
     */
    public void setNumRoleid(String numRoleid) {
        this.numRoleid = numRoleid == null ? null : numRoleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_role.txt_rolename
     *
     * @return the value of t_am_role.txt_rolename
     *
     * @mbggenerated
     */
    public String getTxtRolename() {
        return txtRolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_role.txt_rolename
     *
     * @param txtRolename the value for t_am_role.txt_rolename
     *
     * @mbggenerated
     */
    public void setTxtRolename(String txtRolename) {
        this.txtRolename = txtRolename == null ? null : txtRolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_role.vlu_roletype
     *
     * @return the value of t_am_role.vlu_roletype
     *
     * @mbggenerated
     */
    public String getVluRoletype() {
        return vluRoletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_role.vlu_roletype
     *
     * @param vluRoletype the value for t_am_role.vlu_roletype
     *
     * @mbggenerated
     */
    public void setVluRoletype(String vluRoletype) {
        this.vluRoletype = vluRoletype == null ? null : vluRoletype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_role.ind_msk_sts
     *
     * @return the value of t_am_role.ind_msk_sts
     *
     * @mbggenerated
     */
    public String getIndMskSts() {
        return indMskSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_role.ind_msk_sts
     *
     * @param indMskSts the value for t_am_role.ind_msk_sts
     *
     * @mbggenerated
     */
    public void setIndMskSts(String indMskSts) {
        this.indMskSts = indMskSts == null ? null : indMskSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_role.date_upd_last
     *
     * @return the value of t_am_role.date_upd_last
     *
     * @mbggenerated
     */
    public String getDateUpdLast() {
        return dateUpdLast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_role.date_upd_last
     *
     * @param dateUpdLast the value for t_am_role.date_upd_last
     *
     * @mbggenerated
     */
    public void setDateUpdLast(String dateUpdLast) {
        this.dateUpdLast = dateUpdLast == null ? null : dateUpdLast.trim();
    }
}