package com.ccbs.am.domain;

public class AmRoleMutexInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_rolemutex.num_roleida
     *
     * @mbggenerated
     */
    private String numRoleida;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_rolemutex.num_roleidb
     *
     * @mbggenerated
     */
    private String numRoleidb;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_rolemutex.num_roleida
     *
     * @return the value of t_am_rolemutex.num_roleida
     *
     * @mbggenerated
     */
    public String getNumRoleida() {
        return numRoleida;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_rolemutex.num_roleida
     *
     * @param numRoleida the value for t_am_rolemutex.num_roleida
     *
     * @mbggenerated
     */
    public void setNumRoleida(String numRoleida) {
        this.numRoleida = numRoleida == null ? null : numRoleida.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_rolemutex.num_roleidb
     *
     * @return the value of t_am_rolemutex.num_roleidb
     *
     * @mbggenerated
     */
    public String getNumRoleidb() {
        return numRoleidb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_rolemutex.num_roleidb
     *
     * @param numRoleidb the value for t_am_rolemutex.num_roleidb
     *
     * @mbggenerated
     */
    public void setNumRoleidb(String numRoleidb) {
        this.numRoleidb = numRoleidb == null ? null : numRoleidb.trim();
    }
}