package com.ccbs.am.domain;

public class AmRoleUserInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_role_user.num_roleid
     *
     * @mbggenerated
     */
    private String numRoleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_role_user.num_userid
     *
     * @mbggenerated
     */
    private String numUserid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_role_user.num_roleid
     *
     * @return the value of t_am_role_user.num_roleid
     *
     * @mbggenerated
     */
    public String getNumRoleid() {
        return numRoleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_role_user.num_roleid
     *
     * @param numRoleid the value for t_am_role_user.num_roleid
     *
     * @mbggenerated
     */
    public void setNumRoleid(String numRoleid) {
        this.numRoleid = numRoleid == null ? null : numRoleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_role_user.num_userid
     *
     * @return the value of t_am_role_user.num_userid
     *
     * @mbggenerated
     */
    public String getNumUserid() {
        return numUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_role_user.num_userid
     *
     * @param numUserid the value for t_am_role_user.num_userid
     *
     * @mbggenerated
     */
    public void setNumUserid(String numUserid) {
        this.numUserid = numUserid == null ? null : numUserid.trim();
    }
}