package com.ccbs.am.domain;

public class AmUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_user.num_userid
     *
     * @mbggenerated
     */
    private String numUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_user.txt_username
     *
     * @mbggenerated
     */
    private String txtUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_user.ind_msk_sts
     *
     * @mbggenerated
     */
    private String indMskSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_user.cod_sex
     *
     * @mbggenerated
     */
    private String codSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_user.vlu_pwd
     *
     * @mbggenerated
     */
    private String vluPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_user.cod_pid
     *
     * @mbggenerated
     */
    private String codPid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_user.num_pid
     *
     * @mbggenerated
     */
    private String numPid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_user.txt_title
     *
     * @mbggenerated
     */
    private String txtTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_user.num_phone
     *
     * @mbggenerated
     */
    private String numPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_user.num_mobile
     *
     * @mbggenerated
     */
    private String numMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_user.ind_notice
     *
     * @mbggenerated
     */
    private String indNotice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_user.ind_memeber
     *
     * @mbggenerated
     */
    private String indMemeber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_user.date_open
     *
     * @mbggenerated
     */
    private String dateOpen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_user.vlu_email
     *
     * @mbggenerated
     */
    private String vluEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_user.txt_address
     *
     * @mbggenerated
     */
    private String txtAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_user.date_upd_lsat
     *
     * @mbggenerated
     */
    private String dateUpdLsat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_user.vlu_he_por
     *
     * @mbggenerated
     */
    private byte[] vluHePor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_user.num_userid
     *
     * @return the value of t_am_user.num_userid
     *
     * @mbggenerated
     */
    public String getNumUserid() {
        return numUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_user.num_userid
     *
     * @param numUserid the value for t_am_user.num_userid
     *
     * @mbggenerated
     */
    public void setNumUserid(String numUserid) {
        this.numUserid = numUserid == null ? null : numUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_user.txt_username
     *
     * @return the value of t_am_user.txt_username
     *
     * @mbggenerated
     */
    public String getTxtUsername() {
        return txtUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_user.txt_username
     *
     * @param txtUsername the value for t_am_user.txt_username
     *
     * @mbggenerated
     */
    public void setTxtUsername(String txtUsername) {
        this.txtUsername = txtUsername == null ? null : txtUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_user.ind_msk_sts
     *
     * @return the value of t_am_user.ind_msk_sts
     *
     * @mbggenerated
     */
    public String getIndMskSts() {
        return indMskSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_user.ind_msk_sts
     *
     * @param indMskSts the value for t_am_user.ind_msk_sts
     *
     * @mbggenerated
     */
    public void setIndMskSts(String indMskSts) {
        this.indMskSts = indMskSts == null ? null : indMskSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_user.cod_sex
     *
     * @return the value of t_am_user.cod_sex
     *
     * @mbggenerated
     */
    public String getCodSex() {
        return codSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_user.cod_sex
     *
     * @param codSex the value for t_am_user.cod_sex
     *
     * @mbggenerated
     */
    public void setCodSex(String codSex) {
        this.codSex = codSex == null ? null : codSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_user.vlu_pwd
     *
     * @return the value of t_am_user.vlu_pwd
     *
     * @mbggenerated
     */
    public String getVluPwd() {
        return vluPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_user.vlu_pwd
     *
     * @param vluPwd the value for t_am_user.vlu_pwd
     *
     * @mbggenerated
     */
    public void setVluPwd(String vluPwd) {
        this.vluPwd = vluPwd == null ? null : vluPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_user.cod_pid
     *
     * @return the value of t_am_user.cod_pid
     *
     * @mbggenerated
     */
    public String getCodPid() {
        return codPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_user.cod_pid
     *
     * @param codPid the value for t_am_user.cod_pid
     *
     * @mbggenerated
     */
    public void setCodPid(String codPid) {
        this.codPid = codPid == null ? null : codPid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_user.num_pid
     *
     * @return the value of t_am_user.num_pid
     *
     * @mbggenerated
     */
    public String getNumPid() {
        return numPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_user.num_pid
     *
     * @param numPid the value for t_am_user.num_pid
     *
     * @mbggenerated
     */
    public void setNumPid(String numPid) {
        this.numPid = numPid == null ? null : numPid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_user.txt_title
     *
     * @return the value of t_am_user.txt_title
     *
     * @mbggenerated
     */
    public String getTxtTitle() {
        return txtTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_user.txt_title
     *
     * @param txtTitle the value for t_am_user.txt_title
     *
     * @mbggenerated
     */
    public void setTxtTitle(String txtTitle) {
        this.txtTitle = txtTitle == null ? null : txtTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_user.num_phone
     *
     * @return the value of t_am_user.num_phone
     *
     * @mbggenerated
     */
    public String getNumPhone() {
        return numPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_user.num_phone
     *
     * @param numPhone the value for t_am_user.num_phone
     *
     * @mbggenerated
     */
    public void setNumPhone(String numPhone) {
        this.numPhone = numPhone == null ? null : numPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_user.num_mobile
     *
     * @return the value of t_am_user.num_mobile
     *
     * @mbggenerated
     */
    public String getNumMobile() {
        return numMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_user.num_mobile
     *
     * @param numMobile the value for t_am_user.num_mobile
     *
     * @mbggenerated
     */
    public void setNumMobile(String numMobile) {
        this.numMobile = numMobile == null ? null : numMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_user.ind_notice
     *
     * @return the value of t_am_user.ind_notice
     *
     * @mbggenerated
     */
    public String getIndNotice() {
        return indNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_user.ind_notice
     *
     * @param indNotice the value for t_am_user.ind_notice
     *
     * @mbggenerated
     */
    public void setIndNotice(String indNotice) {
        this.indNotice = indNotice == null ? null : indNotice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_user.ind_memeber
     *
     * @return the value of t_am_user.ind_memeber
     *
     * @mbggenerated
     */
    public String getIndMemeber() {
        return indMemeber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_user.ind_memeber
     *
     * @param indMemeber the value for t_am_user.ind_memeber
     *
     * @mbggenerated
     */
    public void setIndMemeber(String indMemeber) {
        this.indMemeber = indMemeber == null ? null : indMemeber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_user.date_open
     *
     * @return the value of t_am_user.date_open
     *
     * @mbggenerated
     */
    public String getDateOpen() {
        return dateOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_user.date_open
     *
     * @param dateOpen the value for t_am_user.date_open
     *
     * @mbggenerated
     */
    public void setDateOpen(String dateOpen) {
        this.dateOpen = dateOpen == null ? null : dateOpen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_user.vlu_email
     *
     * @return the value of t_am_user.vlu_email
     *
     * @mbggenerated
     */
    public String getVluEmail() {
        return vluEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_user.vlu_email
     *
     * @param vluEmail the value for t_am_user.vlu_email
     *
     * @mbggenerated
     */
    public void setVluEmail(String vluEmail) {
        this.vluEmail = vluEmail == null ? null : vluEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_user.txt_address
     *
     * @return the value of t_am_user.txt_address
     *
     * @mbggenerated
     */
    public String getTxtAddress() {
        return txtAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_user.txt_address
     *
     * @param txtAddress the value for t_am_user.txt_address
     *
     * @mbggenerated
     */
    public void setTxtAddress(String txtAddress) {
        this.txtAddress = txtAddress == null ? null : txtAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_user.date_upd_lsat
     *
     * @return the value of t_am_user.date_upd_lsat
     *
     * @mbggenerated
     */
    public String getDateUpdLsat() {
        return dateUpdLsat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_user.date_upd_lsat
     *
     * @param dateUpdLsat the value for t_am_user.date_upd_lsat
     *
     * @mbggenerated
     */
    public void setDateUpdLsat(String dateUpdLsat) {
        this.dateUpdLsat = dateUpdLsat == null ? null : dateUpdLsat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_user.vlu_he_por
     *
     * @return the value of t_am_user.vlu_he_por
     *
     * @mbggenerated
     */
    public byte[] getVluHePor() {
        return vluHePor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_user.vlu_he_por
     *
     * @param vluHePor the value for t_am_user.vlu_he_por
     *
     * @mbggenerated
     */
    public void setVluHePor(byte[] vluHePor) {
        this.vluHePor = vluHePor;
    }
}