package com.ccbs.am.domain;

public class AmUserLogInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_user_loginfo.num_userid
     *
     * @mbggenerated
     */
    private String numUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_user_loginfo.date_log
     *
     * @mbggenerated
     */
    private String dateLog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_user_loginfo.num_jrn_no
     *
     * @mbggenerated
     */
    private Integer numJrnNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_user_loginfo.num_userid
     *
     * @return the value of t_am_user_loginfo.num_userid
     *
     * @mbggenerated
     */
    public String getNumUserid() {
        return numUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_user_loginfo.num_userid
     *
     * @param numUserid the value for t_am_user_loginfo.num_userid
     *
     * @mbggenerated
     */
    public void setNumUserid(String numUserid) {
        this.numUserid = numUserid == null ? null : numUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_user_loginfo.date_log
     *
     * @return the value of t_am_user_loginfo.date_log
     *
     * @mbggenerated
     */
    public String getDateLog() {
        return dateLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_user_loginfo.date_log
     *
     * @param dateLog the value for t_am_user_loginfo.date_log
     *
     * @mbggenerated
     */
    public void setDateLog(String dateLog) {
        this.dateLog = dateLog == null ? null : dateLog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_user_loginfo.num_jrn_no
     *
     * @return the value of t_am_user_loginfo.num_jrn_no
     *
     * @mbggenerated
     */
    public Integer getNumJrnNo() {
        return numJrnNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_user_loginfo.num_jrn_no
     *
     * @param numJrnNo the value for t_am_user_loginfo.num_jrn_no
     *
     * @mbggenerated
     */
    public void setNumJrnNo(Integer numJrnNo) {
        this.numJrnNo = numJrnNo;
    }
}