package com.ccbs.am.domain;

import java.util.Date;

public class AmUserLogInfo extends AmUserLogInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_am_user_loginfo.date_time
     *
     * @mbggenerated
     */
    private Date dateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_am_user_loginfo.date_time
     *
     * @return the value of t_am_user_loginfo.date_time
     *
     * @mbggenerated
     */
    public Date getDateTime() {
        return dateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_am_user_loginfo.date_time
     *
     * @param dateTime the value for t_am_user_loginfo.date_time
     *
     * @mbggenerated
     */
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
}