package com.ccbs.bs.dao;

import org.apache.ibatis.annotations.Mapper;

import com.ccbs.bs.domain.BsCityInfo;
@Mapper
public interface BsCityInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_city
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String numCity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_city
     *
     * @mbggenerated
     */
    int insert(BsCityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_city
     *
     * @mbggenerated
     */
    int insertSelective(BsCityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_city
     *
     * @mbggenerated
     */
    BsCityInfo selectByPrimaryKey(String numCity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_city
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BsCityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_city
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BsCityInfo record);
}