package com.ccbs.bs.dao;

import org.apache.ibatis.annotations.Mapper;

import com.ccbs.bs.domain.BsFactoryInfo;
@Mapper
public interface BsFactoryInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_factory
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String numFacId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_factory
     *
     * @mbggenerated
     */
    int insert(BsFactoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_factory
     *
     * @mbggenerated
     */
    int insertSelective(BsFactoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_factory
     *
     * @mbggenerated
     */
    BsFactoryInfo selectByPrimaryKey(String numFacId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_factory
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BsFactoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_factory
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BsFactoryInfo record);
}