package com.ccbs.bs.dao;

import org.apache.ibatis.annotations.Mapper;

import com.ccbs.bs.domain.BsMemInfo;
@Mapper
public interface BsMemInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_mem_ser
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String numSer);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_mem_ser
     *
     * @mbggenerated
     */
    int insert(BsMemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_mem_ser
     *
     * @mbggenerated
     */
    int insertSelective(BsMemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_mem_ser
     *
     * @mbggenerated
     */
    BsMemInfo selectByPrimaryKey(String numSer);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_mem_ser
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BsMemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_mem_ser
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BsMemInfo record);
}