package com.ccbs.bs.dao;

import org.apache.ibatis.annotations.Mapper;

import com.ccbs.bs.domain.BsNoticeInfo;
import com.ccbs.bs.domain.BsNoticeInfoKey;
@Mapper
public interface BsNoticeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_notice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BsNoticeInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_notice
     *
     * @mbggenerated
     */
    int insert(BsNoticeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_notice
     *
     * @mbggenerated
     */
    int insertSelective(BsNoticeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_notice
     *
     * @mbggenerated
     */
    BsNoticeInfo selectByPrimaryKey(BsNoticeInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BsNoticeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BsNoticeInfo record);
}