package com.ccbs.bs.dao;

import org.apache.ibatis.annotations.Mapper;

import com.ccbs.bs.domain.BsOvDtalInfo;
import com.ccbs.bs.domain.BsOvDtalInfoKey;
@Mapper
public interface BsOvDtalInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_ov_dtal
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BsOvDtalInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_ov_dtal
     *
     * @mbggenerated
     */
    int insert(BsOvDtalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_ov_dtal
     *
     * @mbggenerated
     */
    int insertSelective(BsOvDtalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_ov_dtal
     *
     * @mbggenerated
     */
    BsOvDtalInfo selectByPrimaryKey(BsOvDtalInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_ov_dtal
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BsOvDtalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_ov_dtal
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BsOvDtalInfo record);
}