package com.ccbs.bs.dao;

import org.apache.ibatis.annotations.Mapper;

import com.ccbs.bs.domain.BsSerMenInfo;
import com.ccbs.bs.domain.BsSerMenInfoKey;
@Mapper
public interface BsSerMenInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_ser_men_rln
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BsSerMenInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_ser_men_rln
     *
     * @mbggenerated
     */
    int insert(BsSerMenInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_ser_men_rln
     *
     * @mbggenerated
     */
    int insertSelective(BsSerMenInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_ser_men_rln
     *
     * @mbggenerated
     */
    BsSerMenInfo selectByPrimaryKey(BsSerMenInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_ser_men_rln
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BsSerMenInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_ser_men_rln
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BsSerMenInfo record);
}