package com.ccbs.bs.domain;

public class BsBusChgInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_bus_chg.num_bus_id
     *
     * @mbggenerated
     */
    private String numBusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_bus_chg.cod_pro
     *
     * @mbggenerated
     */
    private String codPro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_bus_chg.num_city
     *
     * @mbggenerated
     */
    private String numCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_bus_chg.num_industry
     *
     * @mbggenerated
     */
    private String numIndustry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_bus_chg.num_bustyp
     *
     * @mbggenerated
     */
    private String numBustyp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_bus_chg.num_userid
     *
     * @mbggenerated
     */
    private String numUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_bus_chg.txt_bus
     *
     * @mbggenerated
     */
    private String txtBus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_bus_chg.txt_message
     *
     * @mbggenerated
     */
    private String txtMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_bus_chg.ind_msk_msk
     *
     * @mbggenerated
     */
    private String indMskMsk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_bus_chg.date_upd_last
     *
     * @mbggenerated
     */
    private String dateUpdLast;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_bus_chg.num_bus_id
     *
     * @return the value of t_bs_bus_chg.num_bus_id
     *
     * @mbggenerated
     */
    public String getNumBusId() {
        return numBusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_bus_chg.num_bus_id
     *
     * @param numBusId the value for t_bs_bus_chg.num_bus_id
     *
     * @mbggenerated
     */
    public void setNumBusId(String numBusId) {
        this.numBusId = numBusId == null ? null : numBusId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_bus_chg.cod_pro
     *
     * @return the value of t_bs_bus_chg.cod_pro
     *
     * @mbggenerated
     */
    public String getCodPro() {
        return codPro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_bus_chg.cod_pro
     *
     * @param codPro the value for t_bs_bus_chg.cod_pro
     *
     * @mbggenerated
     */
    public void setCodPro(String codPro) {
        this.codPro = codPro == null ? null : codPro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_bus_chg.num_city
     *
     * @return the value of t_bs_bus_chg.num_city
     *
     * @mbggenerated
     */
    public String getNumCity() {
        return numCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_bus_chg.num_city
     *
     * @param numCity the value for t_bs_bus_chg.num_city
     *
     * @mbggenerated
     */
    public void setNumCity(String numCity) {
        this.numCity = numCity == null ? null : numCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_bus_chg.num_industry
     *
     * @return the value of t_bs_bus_chg.num_industry
     *
     * @mbggenerated
     */
    public String getNumIndustry() {
        return numIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_bus_chg.num_industry
     *
     * @param numIndustry the value for t_bs_bus_chg.num_industry
     *
     * @mbggenerated
     */
    public void setNumIndustry(String numIndustry) {
        this.numIndustry = numIndustry == null ? null : numIndustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_bus_chg.num_bustyp
     *
     * @return the value of t_bs_bus_chg.num_bustyp
     *
     * @mbggenerated
     */
    public String getNumBustyp() {
        return numBustyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_bus_chg.num_bustyp
     *
     * @param numBustyp the value for t_bs_bus_chg.num_bustyp
     *
     * @mbggenerated
     */
    public void setNumBustyp(String numBustyp) {
        this.numBustyp = numBustyp == null ? null : numBustyp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_bus_chg.num_userid
     *
     * @return the value of t_bs_bus_chg.num_userid
     *
     * @mbggenerated
     */
    public String getNumUserid() {
        return numUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_bus_chg.num_userid
     *
     * @param numUserid the value for t_bs_bus_chg.num_userid
     *
     * @mbggenerated
     */
    public void setNumUserid(String numUserid) {
        this.numUserid = numUserid == null ? null : numUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_bus_chg.txt_bus
     *
     * @return the value of t_bs_bus_chg.txt_bus
     *
     * @mbggenerated
     */
    public String getTxtBus() {
        return txtBus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_bus_chg.txt_bus
     *
     * @param txtBus the value for t_bs_bus_chg.txt_bus
     *
     * @mbggenerated
     */
    public void setTxtBus(String txtBus) {
        this.txtBus = txtBus == null ? null : txtBus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_bus_chg.txt_message
     *
     * @return the value of t_bs_bus_chg.txt_message
     *
     * @mbggenerated
     */
    public String getTxtMessage() {
        return txtMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_bus_chg.txt_message
     *
     * @param txtMessage the value for t_bs_bus_chg.txt_message
     *
     * @mbggenerated
     */
    public void setTxtMessage(String txtMessage) {
        this.txtMessage = txtMessage == null ? null : txtMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_bus_chg.ind_msk_msk
     *
     * @return the value of t_bs_bus_chg.ind_msk_msk
     *
     * @mbggenerated
     */
    public String getIndMskMsk() {
        return indMskMsk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_bus_chg.ind_msk_msk
     *
     * @param indMskMsk the value for t_bs_bus_chg.ind_msk_msk
     *
     * @mbggenerated
     */
    public void setIndMskMsk(String indMskMsk) {
        this.indMskMsk = indMskMsk == null ? null : indMskMsk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_bus_chg.date_upd_last
     *
     * @return the value of t_bs_bus_chg.date_upd_last
     *
     * @mbggenerated
     */
    public String getDateUpdLast() {
        return dateUpdLast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_bus_chg.date_upd_last
     *
     * @param dateUpdLast the value for t_bs_bus_chg.date_upd_last
     *
     * @mbggenerated
     */
    public void setDateUpdLast(String dateUpdLast) {
        this.dateUpdLast = dateUpdLast == null ? null : dateUpdLast.trim();
    }
}