package com.ccbs.bs.domain;

public class BsCityInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_city.num_city
     *
     * @mbggenerated
     */
    private String numCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_city.cod_pro
     *
     * @mbggenerated
     */
    private String codPro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_city.txt_city_name
     *
     * @mbggenerated
     */
    private String txtCityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_city.ind_msk_sts
     *
     * @mbggenerated
     */
    private String indMskSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_city.ind_hot
     *
     * @mbggenerated
     */
    private String indHot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_city.date_upd_last
     *
     * @mbggenerated
     */
    private String dateUpdLast;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_city.num_city
     *
     * @return the value of t_bs_city.num_city
     *
     * @mbggenerated
     */
    public String getNumCity() {
        return numCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_city.num_city
     *
     * @param numCity the value for t_bs_city.num_city
     *
     * @mbggenerated
     */
    public void setNumCity(String numCity) {
        this.numCity = numCity == null ? null : numCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_city.cod_pro
     *
     * @return the value of t_bs_city.cod_pro
     *
     * @mbggenerated
     */
    public String getCodPro() {
        return codPro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_city.cod_pro
     *
     * @param codPro the value for t_bs_city.cod_pro
     *
     * @mbggenerated
     */
    public void setCodPro(String codPro) {
        this.codPro = codPro == null ? null : codPro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_city.txt_city_name
     *
     * @return the value of t_bs_city.txt_city_name
     *
     * @mbggenerated
     */
    public String getTxtCityName() {
        return txtCityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_city.txt_city_name
     *
     * @param txtCityName the value for t_bs_city.txt_city_name
     *
     * @mbggenerated
     */
    public void setTxtCityName(String txtCityName) {
        this.txtCityName = txtCityName == null ? null : txtCityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_city.ind_msk_sts
     *
     * @return the value of t_bs_city.ind_msk_sts
     *
     * @mbggenerated
     */
    public String getIndMskSts() {
        return indMskSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_city.ind_msk_sts
     *
     * @param indMskSts the value for t_bs_city.ind_msk_sts
     *
     * @mbggenerated
     */
    public void setIndMskSts(String indMskSts) {
        this.indMskSts = indMskSts == null ? null : indMskSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_city.ind_hot
     *
     * @return the value of t_bs_city.ind_hot
     *
     * @mbggenerated
     */
    public String getIndHot() {
        return indHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_city.ind_hot
     *
     * @param indHot the value for t_bs_city.ind_hot
     *
     * @mbggenerated
     */
    public void setIndHot(String indHot) {
        this.indHot = indHot == null ? null : indHot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_city.date_upd_last
     *
     * @return the value of t_bs_city.date_upd_last
     *
     * @mbggenerated
     */
    public String getDateUpdLast() {
        return dateUpdLast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_city.date_upd_last
     *
     * @param dateUpdLast the value for t_bs_city.date_upd_last
     *
     * @mbggenerated
     */
    public void setDateUpdLast(String dateUpdLast) {
        this.dateUpdLast = dateUpdLast == null ? null : dateUpdLast.trim();
    }
}