package com.ccbs.bs.domain;

public class BsFactoryInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_factory.num_fac_id
     *
     * @mbggenerated
     */
    private String numFacId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_factory.cod_pro
     *
     * @mbggenerated
     */
    private String codPro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_factory.num_city
     *
     * @mbggenerated
     */
    private String numCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_factory.num_industry
     *
     * @mbggenerated
     */
    private String numIndustry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_factory.txt_fac
     *
     * @mbggenerated
     */
    private String txtFac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_factory.ind_msk_sts
     *
     * @mbggenerated
     */
    private String indMskSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_factory.date_upd_last
     *
     * @mbggenerated
     */
    private String dateUpdLast;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_factory.num_fac_id
     *
     * @return the value of t_bs_factory.num_fac_id
     *
     * @mbggenerated
     */
    public String getNumFacId() {
        return numFacId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_factory.num_fac_id
     *
     * @param numFacId the value for t_bs_factory.num_fac_id
     *
     * @mbggenerated
     */
    public void setNumFacId(String numFacId) {
        this.numFacId = numFacId == null ? null : numFacId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_factory.cod_pro
     *
     * @return the value of t_bs_factory.cod_pro
     *
     * @mbggenerated
     */
    public String getCodPro() {
        return codPro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_factory.cod_pro
     *
     * @param codPro the value for t_bs_factory.cod_pro
     *
     * @mbggenerated
     */
    public void setCodPro(String codPro) {
        this.codPro = codPro == null ? null : codPro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_factory.num_city
     *
     * @return the value of t_bs_factory.num_city
     *
     * @mbggenerated
     */
    public String getNumCity() {
        return numCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_factory.num_city
     *
     * @param numCity the value for t_bs_factory.num_city
     *
     * @mbggenerated
     */
    public void setNumCity(String numCity) {
        this.numCity = numCity == null ? null : numCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_factory.num_industry
     *
     * @return the value of t_bs_factory.num_industry
     *
     * @mbggenerated
     */
    public String getNumIndustry() {
        return numIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_factory.num_industry
     *
     * @param numIndustry the value for t_bs_factory.num_industry
     *
     * @mbggenerated
     */
    public void setNumIndustry(String numIndustry) {
        this.numIndustry = numIndustry == null ? null : numIndustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_factory.txt_fac
     *
     * @return the value of t_bs_factory.txt_fac
     *
     * @mbggenerated
     */
    public String getTxtFac() {
        return txtFac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_factory.txt_fac
     *
     * @param txtFac the value for t_bs_factory.txt_fac
     *
     * @mbggenerated
     */
    public void setTxtFac(String txtFac) {
        this.txtFac = txtFac == null ? null : txtFac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_factory.ind_msk_sts
     *
     * @return the value of t_bs_factory.ind_msk_sts
     *
     * @mbggenerated
     */
    public String getIndMskSts() {
        return indMskSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_factory.ind_msk_sts
     *
     * @param indMskSts the value for t_bs_factory.ind_msk_sts
     *
     * @mbggenerated
     */
    public void setIndMskSts(String indMskSts) {
        this.indMskSts = indMskSts == null ? null : indMskSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_factory.date_upd_last
     *
     * @return the value of t_bs_factory.date_upd_last
     *
     * @mbggenerated
     */
    public String getDateUpdLast() {
        return dateUpdLast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_factory.date_upd_last
     *
     * @param dateUpdLast the value for t_bs_factory.date_upd_last
     *
     * @mbggenerated
     */
    public void setDateUpdLast(String dateUpdLast) {
        this.dateUpdLast = dateUpdLast == null ? null : dateUpdLast.trim();
    }
}