package com.ccbs.bs.domain;

public class BsIndusInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_industry.num_industry
     *
     * @mbggenerated
     */
    private String numIndustry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_industry.txt_industry
     *
     * @mbggenerated
     */
    private String txtIndustry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_industry.ind_msk_sts
     *
     * @mbggenerated
     */
    private String indMskSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_industry.date_upd_last
     *
     * @mbggenerated
     */
    private String dateUpdLast;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_industry.num_industry
     *
     * @return the value of t_bs_industry.num_industry
     *
     * @mbggenerated
     */
    public String getNumIndustry() {
        return numIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_industry.num_industry
     *
     * @param numIndustry the value for t_bs_industry.num_industry
     *
     * @mbggenerated
     */
    public void setNumIndustry(String numIndustry) {
        this.numIndustry = numIndustry == null ? null : numIndustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_industry.txt_industry
     *
     * @return the value of t_bs_industry.txt_industry
     *
     * @mbggenerated
     */
    public String getTxtIndustry() {
        return txtIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_industry.txt_industry
     *
     * @param txtIndustry the value for t_bs_industry.txt_industry
     *
     * @mbggenerated
     */
    public void setTxtIndustry(String txtIndustry) {
        this.txtIndustry = txtIndustry == null ? null : txtIndustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_industry.ind_msk_sts
     *
     * @return the value of t_bs_industry.ind_msk_sts
     *
     * @mbggenerated
     */
    public String getIndMskSts() {
        return indMskSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_industry.ind_msk_sts
     *
     * @param indMskSts the value for t_bs_industry.ind_msk_sts
     *
     * @mbggenerated
     */
    public void setIndMskSts(String indMskSts) {
        this.indMskSts = indMskSts == null ? null : indMskSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_industry.date_upd_last
     *
     * @return the value of t_bs_industry.date_upd_last
     *
     * @mbggenerated
     */
    public String getDateUpdLast() {
        return dateUpdLast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_industry.date_upd_last
     *
     * @param dateUpdLast the value for t_bs_industry.date_upd_last
     *
     * @mbggenerated
     */
    public void setDateUpdLast(String dateUpdLast) {
        this.dateUpdLast = dateUpdLast == null ? null : dateUpdLast.trim();
    }
}