package com.ccbs.bs.domain;

public class BsInviteInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_invite.num_invite
     *
     * @mbggenerated
     */
    private String numInvite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_invite.cod_pro
     *
     * @mbggenerated
     */
    private String codPro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_invite.num_city
     *
     * @mbggenerated
     */
    private String numCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_invite.num_industry
     *
     * @mbggenerated
     */
    private String numIndustry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_invite.txt_invite
     *
     * @mbggenerated
     */
    private String txtInvite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_invite.num_userid
     *
     * @mbggenerated
     */
    private String numUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_invite.ind_msk_sts
     *
     * @mbggenerated
     */
    private String indMskSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_invite.txt_message
     *
     * @mbggenerated
     */
    private String txtMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_invite.date_upd_last
     *
     * @mbggenerated
     */
    private String dateUpdLast;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_invite.num_invite
     *
     * @return the value of t_bs_invite.num_invite
     *
     * @mbggenerated
     */
    public String getNumInvite() {
        return numInvite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_invite.num_invite
     *
     * @param numInvite the value for t_bs_invite.num_invite
     *
     * @mbggenerated
     */
    public void setNumInvite(String numInvite) {
        this.numInvite = numInvite == null ? null : numInvite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_invite.cod_pro
     *
     * @return the value of t_bs_invite.cod_pro
     *
     * @mbggenerated
     */
    public String getCodPro() {
        return codPro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_invite.cod_pro
     *
     * @param codPro the value for t_bs_invite.cod_pro
     *
     * @mbggenerated
     */
    public void setCodPro(String codPro) {
        this.codPro = codPro == null ? null : codPro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_invite.num_city
     *
     * @return the value of t_bs_invite.num_city
     *
     * @mbggenerated
     */
    public String getNumCity() {
        return numCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_invite.num_city
     *
     * @param numCity the value for t_bs_invite.num_city
     *
     * @mbggenerated
     */
    public void setNumCity(String numCity) {
        this.numCity = numCity == null ? null : numCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_invite.num_industry
     *
     * @return the value of t_bs_invite.num_industry
     *
     * @mbggenerated
     */
    public String getNumIndustry() {
        return numIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_invite.num_industry
     *
     * @param numIndustry the value for t_bs_invite.num_industry
     *
     * @mbggenerated
     */
    public void setNumIndustry(String numIndustry) {
        this.numIndustry = numIndustry == null ? null : numIndustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_invite.txt_invite
     *
     * @return the value of t_bs_invite.txt_invite
     *
     * @mbggenerated
     */
    public String getTxtInvite() {
        return txtInvite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_invite.txt_invite
     *
     * @param txtInvite the value for t_bs_invite.txt_invite
     *
     * @mbggenerated
     */
    public void setTxtInvite(String txtInvite) {
        this.txtInvite = txtInvite == null ? null : txtInvite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_invite.num_userid
     *
     * @return the value of t_bs_invite.num_userid
     *
     * @mbggenerated
     */
    public String getNumUserid() {
        return numUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_invite.num_userid
     *
     * @param numUserid the value for t_bs_invite.num_userid
     *
     * @mbggenerated
     */
    public void setNumUserid(String numUserid) {
        this.numUserid = numUserid == null ? null : numUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_invite.ind_msk_sts
     *
     * @return the value of t_bs_invite.ind_msk_sts
     *
     * @mbggenerated
     */
    public String getIndMskSts() {
        return indMskSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_invite.ind_msk_sts
     *
     * @param indMskSts the value for t_bs_invite.ind_msk_sts
     *
     * @mbggenerated
     */
    public void setIndMskSts(String indMskSts) {
        this.indMskSts = indMskSts == null ? null : indMskSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_invite.txt_message
     *
     * @return the value of t_bs_invite.txt_message
     *
     * @mbggenerated
     */
    public String getTxtMessage() {
        return txtMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_invite.txt_message
     *
     * @param txtMessage the value for t_bs_invite.txt_message
     *
     * @mbggenerated
     */
    public void setTxtMessage(String txtMessage) {
        this.txtMessage = txtMessage == null ? null : txtMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_invite.date_upd_last
     *
     * @return the value of t_bs_invite.date_upd_last
     *
     * @mbggenerated
     */
    public String getDateUpdLast() {
        return dateUpdLast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_invite.date_upd_last
     *
     * @param dateUpdLast the value for t_bs_invite.date_upd_last
     *
     * @mbggenerated
     */
    public void setDateUpdLast(String dateUpdLast) {
        this.dateUpdLast = dateUpdLast == null ? null : dateUpdLast.trim();
    }
}