package com.ccbs.bs.domain;

public class BsMemInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_mem_ser.num_ser
     *
     * @mbggenerated
     */
    private String numSer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_mem_ser.txt_name
     *
     * @mbggenerated
     */
    private String txtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_mem_ser.ind_msk_sts
     *
     * @mbggenerated
     */
    private String indMskSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_mem_ser.txt_messagr
     *
     * @mbggenerated
     */
    private String txtMessagr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_mem_ser.date_upd_last
     *
     * @mbggenerated
     */
    private String dateUpdLast;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_mem_ser.num_ser
     *
     * @return the value of t_bs_mem_ser.num_ser
     *
     * @mbggenerated
     */
    public String getNumSer() {
        return numSer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_mem_ser.num_ser
     *
     * @param numSer the value for t_bs_mem_ser.num_ser
     *
     * @mbggenerated
     */
    public void setNumSer(String numSer) {
        this.numSer = numSer == null ? null : numSer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_mem_ser.txt_name
     *
     * @return the value of t_bs_mem_ser.txt_name
     *
     * @mbggenerated
     */
    public String getTxtName() {
        return txtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_mem_ser.txt_name
     *
     * @param txtName the value for t_bs_mem_ser.txt_name
     *
     * @mbggenerated
     */
    public void setTxtName(String txtName) {
        this.txtName = txtName == null ? null : txtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_mem_ser.ind_msk_sts
     *
     * @return the value of t_bs_mem_ser.ind_msk_sts
     *
     * @mbggenerated
     */
    public String getIndMskSts() {
        return indMskSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_mem_ser.ind_msk_sts
     *
     * @param indMskSts the value for t_bs_mem_ser.ind_msk_sts
     *
     * @mbggenerated
     */
    public void setIndMskSts(String indMskSts) {
        this.indMskSts = indMskSts == null ? null : indMskSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_mem_ser.txt_messagr
     *
     * @return the value of t_bs_mem_ser.txt_messagr
     *
     * @mbggenerated
     */
    public String getTxtMessagr() {
        return txtMessagr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_mem_ser.txt_messagr
     *
     * @param txtMessagr the value for t_bs_mem_ser.txt_messagr
     *
     * @mbggenerated
     */
    public void setTxtMessagr(String txtMessagr) {
        this.txtMessagr = txtMessagr == null ? null : txtMessagr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_mem_ser.date_upd_last
     *
     * @return the value of t_bs_mem_ser.date_upd_last
     *
     * @mbggenerated
     */
    public String getDateUpdLast() {
        return dateUpdLast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_mem_ser.date_upd_last
     *
     * @param dateUpdLast the value for t_bs_mem_ser.date_upd_last
     *
     * @mbggenerated
     */
    public void setDateUpdLast(String dateUpdLast) {
        this.dateUpdLast = dateUpdLast == null ? null : dateUpdLast.trim();
    }
}