package com.ccbs.bs.domain;

import java.math.BigDecimal;

public class BsOvDtalInfo extends BsOvDtalInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_ov_dtal.ind_msk_proc
     *
     * @mbggenerated
     */
    private String indMskProc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_ov_dtal.cod_tr_type
     *
     * @mbggenerated
     */
    private String codTrType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_ov_dtal.amt_tr
     *
     * @mbggenerated
     */
    private BigDecimal amtTr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_ov_dtal.amt_post
     *
     * @mbggenerated
     */
    private BigDecimal amtPost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_ov_dtal.bal_cr
     *
     * @mbggenerated
     */
    private BigDecimal balCr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_ov_dtal.txt_mer_name
     *
     * @mbggenerated
     */
    private String txtMerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_ov_dtal.num_jrn_weixin
     *
     * @mbggenerated
     */
    private String numJrnWeixin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_ov_dtal.ind_msk_proc
     *
     * @return the value of t_bs_ov_dtal.ind_msk_proc
     *
     * @mbggenerated
     */
    public String getIndMskProc() {
        return indMskProc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_ov_dtal.ind_msk_proc
     *
     * @param indMskProc the value for t_bs_ov_dtal.ind_msk_proc
     *
     * @mbggenerated
     */
    public void setIndMskProc(String indMskProc) {
        this.indMskProc = indMskProc == null ? null : indMskProc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_ov_dtal.cod_tr_type
     *
     * @return the value of t_bs_ov_dtal.cod_tr_type
     *
     * @mbggenerated
     */
    public String getCodTrType() {
        return codTrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_ov_dtal.cod_tr_type
     *
     * @param codTrType the value for t_bs_ov_dtal.cod_tr_type
     *
     * @mbggenerated
     */
    public void setCodTrType(String codTrType) {
        this.codTrType = codTrType == null ? null : codTrType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_ov_dtal.amt_tr
     *
     * @return the value of t_bs_ov_dtal.amt_tr
     *
     * @mbggenerated
     */
    public BigDecimal getAmtTr() {
        return amtTr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_ov_dtal.amt_tr
     *
     * @param amtTr the value for t_bs_ov_dtal.amt_tr
     *
     * @mbggenerated
     */
    public void setAmtTr(BigDecimal amtTr) {
        this.amtTr = amtTr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_ov_dtal.amt_post
     *
     * @return the value of t_bs_ov_dtal.amt_post
     *
     * @mbggenerated
     */
    public BigDecimal getAmtPost() {
        return amtPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_ov_dtal.amt_post
     *
     * @param amtPost the value for t_bs_ov_dtal.amt_post
     *
     * @mbggenerated
     */
    public void setAmtPost(BigDecimal amtPost) {
        this.amtPost = amtPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_ov_dtal.bal_cr
     *
     * @return the value of t_bs_ov_dtal.bal_cr
     *
     * @mbggenerated
     */
    public BigDecimal getBalCr() {
        return balCr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_ov_dtal.bal_cr
     *
     * @param balCr the value for t_bs_ov_dtal.bal_cr
     *
     * @mbggenerated
     */
    public void setBalCr(BigDecimal balCr) {
        this.balCr = balCr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_ov_dtal.txt_mer_name
     *
     * @return the value of t_bs_ov_dtal.txt_mer_name
     *
     * @mbggenerated
     */
    public String getTxtMerName() {
        return txtMerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_ov_dtal.txt_mer_name
     *
     * @param txtMerName the value for t_bs_ov_dtal.txt_mer_name
     *
     * @mbggenerated
     */
    public void setTxtMerName(String txtMerName) {
        this.txtMerName = txtMerName == null ? null : txtMerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_ov_dtal.num_jrn_weixin
     *
     * @return the value of t_bs_ov_dtal.num_jrn_weixin
     *
     * @mbggenerated
     */
    public String getNumJrnWeixin() {
        return numJrnWeixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_ov_dtal.num_jrn_weixin
     *
     * @param numJrnWeixin the value for t_bs_ov_dtal.num_jrn_weixin
     *
     * @mbggenerated
     */
    public void setNumJrnWeixin(String numJrnWeixin) {
        this.numJrnWeixin = numJrnWeixin == null ? null : numJrnWeixin.trim();
    }
}