package com.ccbs.bs.domain;

public class BsOvDtalInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_ov_dtal.num_userid
     *
     * @mbggenerated
     */
    private String numUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_ov_dtal.num_acc_pct
     *
     * @mbggenerated
     */
    private String numAccPct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_ov_dtal.date_post
     *
     * @mbggenerated
     */
    private String datePost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_ov_dtal.num_jrn_post
     *
     * @mbggenerated
     */
    private Integer numJrnPost;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_ov_dtal.num_userid
     *
     * @return the value of t_bs_ov_dtal.num_userid
     *
     * @mbggenerated
     */
    public String getNumUserid() {
        return numUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_ov_dtal.num_userid
     *
     * @param numUserid the value for t_bs_ov_dtal.num_userid
     *
     * @mbggenerated
     */
    public void setNumUserid(String numUserid) {
        this.numUserid = numUserid == null ? null : numUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_ov_dtal.num_acc_pct
     *
     * @return the value of t_bs_ov_dtal.num_acc_pct
     *
     * @mbggenerated
     */
    public String getNumAccPct() {
        return numAccPct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_ov_dtal.num_acc_pct
     *
     * @param numAccPct the value for t_bs_ov_dtal.num_acc_pct
     *
     * @mbggenerated
     */
    public void setNumAccPct(String numAccPct) {
        this.numAccPct = numAccPct == null ? null : numAccPct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_ov_dtal.date_post
     *
     * @return the value of t_bs_ov_dtal.date_post
     *
     * @mbggenerated
     */
    public String getDatePost() {
        return datePost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_ov_dtal.date_post
     *
     * @param datePost the value for t_bs_ov_dtal.date_post
     *
     * @mbggenerated
     */
    public void setDatePost(String datePost) {
        this.datePost = datePost == null ? null : datePost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_ov_dtal.num_jrn_post
     *
     * @return the value of t_bs_ov_dtal.num_jrn_post
     *
     * @mbggenerated
     */
    public Integer getNumJrnPost() {
        return numJrnPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_ov_dtal.num_jrn_post
     *
     * @param numJrnPost the value for t_bs_ov_dtal.num_jrn_post
     *
     * @mbggenerated
     */
    public void setNumJrnPost(Integer numJrnPost) {
        this.numJrnPost = numJrnPost;
    }
}