package com.ccbs.bs.domain;

public class BsTypInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_bustyp.num_bustyp
     *
     * @mbggenerated
     */
    private String numBustyp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_bustyp.txt_bustyp
     *
     * @mbggenerated
     */
    private String txtBustyp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_bustyp.ind_msk_sts
     *
     * @mbggenerated
     */
    private String indMskSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_bustyp.date_upd_last
     *
     * @mbggenerated
     */
    private String dateUpdLast;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_bustyp.num_bustyp
     *
     * @return the value of t_bs_bustyp.num_bustyp
     *
     * @mbggenerated
     */
    public String getNumBustyp() {
        return numBustyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_bustyp.num_bustyp
     *
     * @param numBustyp the value for t_bs_bustyp.num_bustyp
     *
     * @mbggenerated
     */
    public void setNumBustyp(String numBustyp) {
        this.numBustyp = numBustyp == null ? null : numBustyp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_bustyp.txt_bustyp
     *
     * @return the value of t_bs_bustyp.txt_bustyp
     *
     * @mbggenerated
     */
    public String getTxtBustyp() {
        return txtBustyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_bustyp.txt_bustyp
     *
     * @param txtBustyp the value for t_bs_bustyp.txt_bustyp
     *
     * @mbggenerated
     */
    public void setTxtBustyp(String txtBustyp) {
        this.txtBustyp = txtBustyp == null ? null : txtBustyp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_bustyp.ind_msk_sts
     *
     * @return the value of t_bs_bustyp.ind_msk_sts
     *
     * @mbggenerated
     */
    public String getIndMskSts() {
        return indMskSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_bustyp.ind_msk_sts
     *
     * @param indMskSts the value for t_bs_bustyp.ind_msk_sts
     *
     * @mbggenerated
     */
    public void setIndMskSts(String indMskSts) {
        this.indMskSts = indMskSts == null ? null : indMskSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_bustyp.date_upd_last
     *
     * @return the value of t_bs_bustyp.date_upd_last
     *
     * @mbggenerated
     */
    public String getDateUpdLast() {
        return dateUpdLast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_bustyp.date_upd_last
     *
     * @param dateUpdLast the value for t_bs_bustyp.date_upd_last
     *
     * @mbggenerated
     */
    public void setDateUpdLast(String dateUpdLast) {
        this.dateUpdLast = dateUpdLast == null ? null : dateUpdLast.trim();
    }
}