package com.ccbs.am.dao;

import org.apache.ibatis.annotations.Mapper;

import com.ccbs.am.domain.AmMenuInfo;
@Mapper
public interface AmMenuInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String numMenuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_menu
     *
     * @mbggenerated
     */
    int insert(AmMenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_menu
     *
     * @mbggenerated
     */
    int insertSelective(AmMenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_menu
     *
     * @mbggenerated
     */
    AmMenuInfo selectByPrimaryKey(String numMenuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AmMenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AmMenuInfo record);
}