package com.ccbs.am.dao;

import org.apache.ibatis.annotations.Mapper;

import com.ccbs.am.domain.AmPremMenuInfo;
import com.ccbs.am.domain.AmPremMenuInfoKey;
@Mapper
public interface AmPremMenuInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_prem_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(AmPremMenuInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_prem_menu
     *
     * @mbggenerated
     */
    int insert(AmPremMenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_prem_menu
     *
     * @mbggenerated
     */
    int insertSelective(AmPremMenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_prem_menu
     *
     * @mbggenerated
     */
    AmPremMenuInfo selectByPrimaryKey(AmPremMenuInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_prem_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AmPremMenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_prem_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AmPremMenuInfo record);
}