package com.ccbs.am.dao;

import org.apache.ibatis.annotations.Mapper;

import com.ccbs.am.domain.AmPremRoleInfo;
import com.ccbs.am.domain.AmPremRoleInfoKey;
@Mapper
public interface AmPremRoleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_prem_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(AmPremRoleInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_prem_role
     *
     * @mbggenerated
     */
    int insert(AmPremRoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_prem_role
     *
     * @mbggenerated
     */
    int insertSelective(AmPremRoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_prem_role
     *
     * @mbggenerated
     */
    AmPremRoleInfo selectByPrimaryKey(AmPremRoleInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_prem_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AmPremRoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_prem_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AmPremRoleInfo record);
}