package com.ccbs.am.dao;

import org.apache.ibatis.annotations.Mapper;

import com.ccbs.am.domain.AmPremInfo;
@Mapper
public interface AmPremInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_premision
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String numPremid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_premision
     *
     * @mbggenerated
     */
    int insert(AmPremInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_premision
     *
     * @mbggenerated
     */
    int insertSelective(AmPremInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_premision
     *
     * @mbggenerated
     */
    AmPremInfo selectByPrimaryKey(String numPremid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_premision
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AmPremInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_premision
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AmPremInfo record);
}