package com.ccbs.am.dao;

import org.apache.ibatis.annotations.Mapper;

import com.ccbs.am.domain.AmRoleMutexInfo;
import com.ccbs.am.domain.AmRoleMutexInfoKey;
@Mapper
public interface AmRoleMutexInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_rolemutex
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(AmRoleMutexInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_rolemutex
     *
     * @mbggenerated
     */
    int insert(AmRoleMutexInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_rolemutex
     *
     * @mbggenerated
     */
    int insertSelective(AmRoleMutexInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_rolemutex
     *
     * @mbggenerated
     */
    AmRoleMutexInfo selectByPrimaryKey(AmRoleMutexInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_rolemutex
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AmRoleMutexInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_rolemutex
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AmRoleMutexInfo record);
}