package com.ccbs.am.dao;

import org.apache.ibatis.annotations.Mapper;

import com.ccbs.am.domain.AmRoleInfo;
@Mapper
public interface AmRoleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String numRoleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_role
     *
     * @mbggenerated
     */
    int insert(AmRoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_role
     *
     * @mbggenerated
     */
    int insertSelective(AmRoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_role
     *
     * @mbggenerated
     */
    AmRoleInfo selectByPrimaryKey(String numRoleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AmRoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AmRoleInfo record);
}