package com.ccbs.am.dao;

import org.apache.ibatis.annotations.Mapper;

import com.ccbs.am.domain.AmUserInfo;

@Mapper
public interface AmUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String numUserid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_user
     *
     * @mbggenerated
     */
    int insert(AmUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_user
     *
     * @mbggenerated
     */
    int insertSelective(AmUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_user
     *
     * @mbggenerated
     */
    AmUserInfo selectByPrimaryKey(String numUserid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AmUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(AmUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AmUserInfo record);
}