package com.ccbs.am.dao;

import org.apache.ibatis.annotations.Mapper;

import com.ccbs.am.domain.AmUserLogInfo;
import com.ccbs.am.domain.AmUserLogInfoKey;
@Mapper
public interface AmUserLogInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_user_loginfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(AmUserLogInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_user_loginfo
     *
     * @mbggenerated
     */
    int insert(AmUserLogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_user_loginfo
     *
     * @mbggenerated
     */
    int insertSelective(AmUserLogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_user_loginfo
     *
     * @mbggenerated
     */
    AmUserLogInfo selectByPrimaryKey(AmUserLogInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_user_loginfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AmUserLogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_am_user_loginfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AmUserLogInfo record);
}